# This is a basic workflow to help you get started with Actions

name: Maven clean compile test

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for develop branch
  pull_request:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Maven clean compile
        run: mvn clean compile
        
      # Runs a single command using the runners shell
      - name: Maven test
        run: mvn test

      - name: Deploy to Heroku
        # uses: AkhileshNS/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{secrets.HEROKU_DEPLOY}}
          # Email that you use with heroku
          heroku_email: pixel38320@gmail.com
          # The appname to use for deploying/updating
          heroku_app_name: developecom
          # The branch that you would like to deploy to Heroku
          branch: develop
